-- MySQL Script generated by MySQL Workbench
-- Sat Dec 13 15:05:12 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FLYTAU
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FLYTAU
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FLYTAU` DEFAULT CHARACTER SET utf8 ;
USE `FLYTAU` ;

-- -----------------------------------------------------
-- Table `FLYTAU`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FLYTAU`.`Employee` (
  `employee_id` VARCHAR(9) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `phone_num` VARCHAR(10) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `st_num` INT NULL DEFAULT NULL,
  `role` ENUM('Manager', 'Pilot', 'Flight_Attendant') NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FLYTAU`.`Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FLYTAU`.`Manager` (
  `manager_employee_id` VARCHAR(9) NOT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`manager_employee_id`),
  CONSTRAINT `manager_employee_id`
    FOREIGN KEY (`manager_employee_id`)
    REFERENCES `FLYTAU`.`Employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FLYTAU`.`Steward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FLYTAU`.`Steward` (
  `steward_employee_id` VARCHAR(9) NOT NULL,
  `long_flight_qualified` BINARY(1) NULL DEFAULT NULL,
  PRIMARY KEY (`steward_employee_id`),
  CONSTRAINT `steward_employee_id`
    FOREIGN KEY (`steward_employee_id`)
    REFERENCES `FLYTAU`.`Employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FLYTAU`.`Pilot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FLYTAU`.`Pilot` (
  `pilot_employee_id` VARCHAR(9) NOT NULL,
  `long_flight_qualified` BINARY(1) NULL DEFAULT NULL,
  PRIMARY KEY (`pilot_employee_id`),
  CONSTRAINT `pilot_employee_id`
    FOREIGN KEY (`pilot_employee_id`)
    REFERENCES `FLYTAU`.`Employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FLYTAU`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FLYTAU`.`Customer` (
  `customer_email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `passport` VARCHAR(45) NULL DEFAULT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `reg_date` DATE NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FLYTAU`.`Guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FLYTAU`.`Guest` (
  `guest_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`guest_email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FLYTAU`.`Customer_Phone_Numbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FLYTAU`.`Customer_Phone_Numbers` (
  `phone_customer_email` VARCHAR(45) NOT NULL,
  `phone_num` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`phone_customer_email`, `phone_num`),
  CONSTRAINT `phone_customer_email`
    FOREIGN KEY (`phone_customer_email`)
    REFERENCES `FLYTAU`.`Customer` (`customer_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FLYTAU`.`Plane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FLYTAU`.`Plane` (
  `plane_id` VARCHAR(45) NOT NULL,
  `size` ENUM('small', 'large') NULL DEFAULT NULL,
  `purchase_date` DATE NULL DEFAULT NULL,
  `manufacturer` ENUM('Boeing', 'Airbus', 'Dassault') NULL DEFAULT NULL,
  PRIMARY KEY (`plane_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FLYTAU`.`Route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FLYTAU`.`Route` (
  `origin_airport` VARCHAR(45) NOT NULL,
  `destination_airport` VARCHAR(45) NOT NULL,
  `duration` TIME NULL,
  PRIMARY KEY (`destination_airport`, `origin_airport`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FLYTAU`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FLYTAU`.`Flight` (
  `flight_id` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `origin_airport` VARCHAR(45) NULL DEFAULT NULL,
  `destination_airport` VARCHAR(45) NULL DEFAULT NULL,
  `duration` TIME NULL DEFAULT NULL,
  `flight_length` ENUM('short', 'long') GENERATED ALWAYS AS (CASE
    WHEN duration > '05:00:00' THEN 'long'
    ELSE 'short'
  END) VIRTUAL,
  `departure` DATETIME NULL DEFAULT NULL,
  `arrival` DATETIME GENERATED ALWAYS AS (ADDTIME(departure, duration)) VIRTUAL,
  `plane_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`flight_id`),
  INDEX `plane_id_idx` (`plane_id` ASC) VISIBLE,
  INDEX `origin_airport_idx` (`origin_airport` ASC) VISIBLE,
  INDEX `destination_airport_idx` (`destination_airport` ASC) VISIBLE,
  CONSTRAINT `plane_id`
    FOREIGN KEY (`plane_id`)
    REFERENCES `FLYTAU`.`Plane` (`plane_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT `fk_flight_route`
  FOREIGN KEY (`destination_airport`, `origin_airport`)
  REFERENCES `FLYTAU`.`Route` (`destination_airport`, `origin_airport`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `FLYTAU`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FLYTAU`.`Orders` (
  `code` VARCHAR(45) NOT NULL,
  `status` ENUM('active', 'full', 'completed', 'cancelled') NULL DEFAULT NULL,
  `total_price` INT NULL DEFAULT NULL,
  `order_date` DATE NULL DEFAULT NULL,
  `flight_id` VARCHAR(45) NULL DEFAULT NULL,
  `guest_email` VARCHAR(45) NULL DEFAULT NULL,
  `customer_email` VARCHAR(45) NULL,
  PRIMARY KEY (`code`),
  INDEX `flight_id_idx` (`flight_id` ASC) VISIBLE,
  INDEX `customer_email_idx` (`customer_email` ASC) VISIBLE,
  CONSTRAINT `flight_id`
    FOREIGN KEY (`flight_id`)
    REFERENCES `FLYTAU`.`Flight` (`flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `guest_email`
    FOREIGN KEY (`guest_email`)
    REFERENCES `FLYTAU`.`Guest` (`guest_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_email`
    FOREIGN KEY (`customer_email`)
    REFERENCES `FLYTAU`.`Customer` (`customer_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FLYTAU`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FLYTAU`.`Class` (
  `seat_row` INT NOT NULL,
  `seat_position` VARCHAR(1) NOT NULL,
  `class_type` ENUM('economy','business') NULL DEFAULT NULL,
  `seat_price` INT NULL DEFAULT NULL,
  PRIMARY KEY (`seat_row`, `seat_position`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FLYTAU`.`Seats_in_Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FLYTAU`.`Seats_in_Order` (
  `seat_row` INT NOT NULL,
  `seat_position` VARCHAR(1) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `seats_plane_id` VARCHAR(45) NOT NULL,
  `price` INT NULL DEFAULT NULL,
  PRIMARY KEY (`seat_row`, `seat_position`, `code`, `seats_plane_id`),
  INDEX `seat_position_idx` (`seat_position` ASC) VISIBLE,
  INDEX `code_idx` (`code` ASC) VISIBLE,
  INDEX `plane_id_idx` (`seats_plane_id` ASC) VISIBLE,
CONSTRAINT `fk_seatsinorder_class`
  FOREIGN KEY (`seat_row`, `seat_position`)
  REFERENCES `FLYTAU`.`Class` (`seat_row`, `seat_position`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT `code`
    FOREIGN KEY (`code`)
    REFERENCES `FLYTAU`.`Orders` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `seats_plane_id`
    FOREIGN KEY (`seats_plane_id`)
    REFERENCES `FLYTAU`.`Plane` (`plane_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FLYTAU`.`Employees_on_Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FLYTAU`.`Employees_on_Flight` (
  `employee_on_flight_flight_id` VARCHAR(45) NOT NULL,
  `employee_on_flight_employee_id` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`employee_on_flight_flight_id`, `employee_on_flight_employee_id`),
  INDEX `employee_id_idx` (`employee_on_flight_employee_id` ASC) VISIBLE,
  CONSTRAINT `employee_on_flight_flight_id`
    FOREIGN KEY (`employee_on_flight_flight_id`)
    REFERENCES `FLYTAU`.`Flight` (`flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employee_on_flight_employee_id`
    FOREIGN KEY (`employee_on_flight_employee_id`)
    REFERENCES `FLYTAU`.`Employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FLYTAU`.`Manager_of_Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FLYTAU`.`Manager_of_Flight` (
  `manager_of_flight_employee_id` VARCHAR(9) NOT NULL,
  `manager_of_flight_flight_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`manager_of_flight_employee_id`, `manager_of_flight_flight_id`),
  INDEX `flight_id_idx` (`manager_of_flight_flight_id` ASC) VISIBLE,
  CONSTRAINT `manager_of_flight_employee_id`
    FOREIGN KEY (`manager_of_flight_employee_id`)
    REFERENCES `FLYTAU`.`Manager` (`manager_employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `manager_of_flight_flight_id`
    FOREIGN KEY (`manager_of_flight_flight_id`)
    REFERENCES `FLYTAU`.`Flight` (`flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

