-- MySQL Script generated by MySQL Workbench
-- Sat Dec 27 13:06:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `customer_email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `passport` VARCHAR(45) NULL DEFAULT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `reg_date` DATE NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Guest` (
  `guest_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`guest_email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_Phone_Numbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_Phone_Numbers` (
  `phone_customer_email` VARCHAR(45) NOT NULL,
  `phone_num` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`phone_customer_email`, `phone_num`),
  CONSTRAINT `phone_customer_email`
    FOREIGN KEY (`phone_customer_email`)
    REFERENCES `mydb`.`Customer` (`customer_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plane` (
  `plane_id` VARCHAR(45) NOT NULL,
  `size` ENUM('small', 'large') NULL DEFAULT NULL,
  `purchase_date` DATE NULL DEFAULT NULL,
  `manufacturer` ENUM('Boeing', 'Airbus', 'Dassault') NULL DEFAULT NULL,
  PRIMARY KEY (`plane_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Route` (
  `origin_airport` VARCHAR(45) NOT NULL,
  `destination_airport` VARCHAR(45) NOT NULL,
  `duration` TIME NULL,
  PRIMARY KEY (`destination_airport`, `origin_airport`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight` (
  `flight_id` VARCHAR(45) NOT NULL,
  `status` ENUM('active', 'completed', 'cancelled by user', 'cancelled by system') NULL DEFAULT NULL,
  `origin_airport` VARCHAR(45) NULL DEFAULT NULL,
  `destination_airport` VARCHAR(45) NULL DEFAULT NULL,
  `duration` TIME NULL DEFAULT NULL,
  `flight_length` ENUM('short', 'long') GENERATED ALWAYS AS (CASE
    WHEN duration > '05:00:00' THEN 'long'
    ELSE 'short'
  END) VIRTUAL,
  `departure` DATETIME NULL DEFAULT NULL,
  `arrival` DATETIME GENERATED ALWAYS AS (ADDTIME(departure, duration)) VIRTUAL,
  `plane_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`flight_id`),
  INDEX `plane_id_idx` (`plane_id` ASC) VISIBLE,
  INDEX `origin_airport_idx` (`origin_airport` ASC) VISIBLE,
  INDEX `destination_airport_idx` (`destination_airport` ASC) VISIBLE,
  CONSTRAINT `plane_id`
    FOREIGN KEY (`plane_id`)
    REFERENCES `mydb`.`Plane` (`plane_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `origin_airport`
    FOREIGN KEY (`origin_airport`)
    REFERENCES `mydb`.`Route` (`origin_airport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `destination_airport`
    FOREIGN KEY (`destination_airport`)
    REFERENCES `mydb`.`Route` (`destination_airport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `code` VARCHAR(45) NOT NULL,
  `status` ENUM('active', 'full', 'completed', 'cancelled') NULL DEFAULT NULL,
  `total_price` INT NULL DEFAULT NULL,
  `order_date` DATE NULL DEFAULT NULL,
  `flight_id` VARCHAR(45) NULL DEFAULT NULL,
  `guest_email` VARCHAR(45) NULL DEFAULT NULL,
  `customer_email` VARCHAR(45) NULL,
  PRIMARY KEY (`code`),
  INDEX `flight_id_idx` (`flight_id` ASC) VISIBLE,
  INDEX `customer_email_idx` (`customer_email` ASC) VISIBLE,
  CONSTRAINT `flight_id`
    FOREIGN KEY (`flight_id`)
    REFERENCES `mydb`.`Flight` (`flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `guest_email`
    FOREIGN KEY (`guest_email`)
    REFERENCES `mydb`.`Guest` (`guest_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_email`
    FOREIGN KEY (`customer_email`)
    REFERENCES `mydb`.`Customer` (`customer_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Class` (
  `plane_id` VARCHAR(45) NOT NULL,
  `seat_row` INT NOT NULL,
  `seat_position` VARCHAR(1) NOT NULL,
  `class_type` ENUM('economy', 'business') NULL DEFAULT NULL,
  `seat_price` INT NULL DEFAULT NULL,
  PRIMARY KEY (`plane_id`, `seat_row`, `seat_position`),
  CONSTRAINT `plane_id`
    FOREIGN KEY (`plane_id`)
    REFERENCES `mydb`.`Plane` (`plane_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seats_in_Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seats_in_Order` (
  `seat_row` INT NOT NULL,
  `seat_position` VARCHAR(1) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `seats_plane_id` VARCHAR(45) NOT NULL,
  `price` INT NULL DEFAULT NULL,
  PRIMARY KEY (`seat_row`, `seat_position`, `code`, `seats_plane_id`),
  INDEX `seat_position_idx` (`seat_position` ASC) VISIBLE,
  INDEX `code_idx` (`code` ASC) VISIBLE,
  INDEX `plane_id_idx` (`seats_plane_id` ASC) VISIBLE,
  CONSTRAINT `seat_row`
    FOREIGN KEY (`seat_row`)
    REFERENCES `mydb`.`Class` (`seat_row`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `seat_position`
    FOREIGN KEY (`seat_position`)
    REFERENCES `mydb`.`Class` (`seat_position`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `code`
    FOREIGN KEY (`code`)
    REFERENCES `mydb`.`Orders` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `seats_plane_id`
    FOREIGN KEY (`seats_plane_id`)
    REFERENCES `mydb`.`Plane` (`plane_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pilot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pilot` (
  `pilot_id` VARCHAR(9) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `phone_num` VARCHAR(10) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `st_num` INT NULL DEFAULT NULL,
  `long_flight_qualified` BINARY(1) NULL,
  PRIMARY KEY (`pilot_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pilots_on_Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pilots_on_Flight` (
  `pilot_on_flight_flight_id` VARCHAR(45) NOT NULL,
  `pilot_on_flight_pilot_id` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`pilot_on_flight_flight_id`, `pilot_on_flight_pilot_id`),
  INDEX `pilot_employee_id_idx` (`pilot_on_flight_pilot_id` ASC) VISIBLE,
  CONSTRAINT `pilots_on_flight_flight_id`
    FOREIGN KEY (`pilot_on_flight_flight_id`)
    REFERENCES `mydb`.`Flight` (`flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pilot_on_flight_pilot_id`
    FOREIGN KEY (`pilot_on_flight_pilot_id`)
    REFERENCES `mydb`.`Pilot` (`pilot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manager` (
  `manager_id` VARCHAR(9) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `phone_num` VARCHAR(10) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `st_num` INT NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`manager_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manager_of_Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manager_of_Flight` (
  `manager_of_flight_manager_id` VARCHAR(9) NOT NULL,
  `manager_of_flight_flight_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`manager_of_flight_manager_id`, `manager_of_flight_flight_id`),
  INDEX `flight_id_idx` (`manager_of_flight_flight_id` ASC) VISIBLE,
  CONSTRAINT `manager_of_flight_flight_id`
    FOREIGN KEY (`manager_of_flight_flight_id`)
    REFERENCES `mydb`.`Flight` (`flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `manager_of_flight_manager_id`
    FOREIGN KEY (`manager_of_flight_manager_id`)
    REFERENCES `mydb`.`Manager` (`manager_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flight_Attendant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight_Attendant` (
  `flight_attendant_id` VARCHAR(9) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `phone_num` VARCHAR(10) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `st_num` INT NULL DEFAULT NULL,
  `long_flight_qualified` BINARY(1) NULL,
  PRIMARY KEY (`flight_attendant_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FA_on_Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FA_on_Flight` (
  `fa_on_flight_flight_id` VARCHAR(45) NOT NULL,
  `fa_on_flight_fa_id` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`fa_on_flight_flight_id`, `fa_on_flight_fa_id`),
  INDEX `fa_employee_id_idx` (`fa_on_flight_fa_id` ASC) VISIBLE,
  CONSTRAINT `fa_on_flight_flight_id`
    FOREIGN KEY (`fa_on_flight_flight_id`)
    REFERENCES `mydb`.`Flight` (`flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fa_on_flight_fa_id`
    FOREIGN KEY (`fa_on_flight_fa_id`)
    REFERENCES `mydb`.`Flight_Attendant` (`flight_attendant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
